macos_min_version:             # [osx and x86_64]
  - 10.14                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.14                      # [osx and x86_64]
c_compiler_version:            # [osx]
  - 17                         # [osx]
cxx_compiler_version:          # [osx]
  - 17                         # [osx]
