macos_min_version:             # [osx and x86_64]
  - 10.14                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.14                      # [osx and x86_64]
c_compiler_version:            # [osx]
  - 17                         # [osx]
cxx_compiler_version:          # [osx]
  - 17                         # [osx]
docker_image:                                   # [linux]
  - quay.io/condaforge/linux-anvil-cos7-x86_64  # [linux]
  
