{% set name = "libsdformat" %}
{% set version = "6.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osrf/sdformat/archive/sdformat{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 88d0fe2fcf27842f33d60e087e9142312c0392d55dfb250f2a66e66d55eb40dd
    patches:
      - use-external-deps.patch
      - fix-install-location.patch

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - ninja                              # [not win]
    - ruby                               # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-math4
    - urdfdom
    - boost-cpp >=1.72
    - tinyxml
    - console_bridge 1.0.*
  run:
    - libignition-math4
    - urdfdom
    - tinyxml
    - console_bridge 1.0.*

test:
  commands:
    - test -f ${PREFIX}/include/sdformat-6.2/sdf/sdf.hh  # [not win]
    - test -f ${PREFIX}/lib/libsdformat.so  # [linux]
    - test -f ${PREFIX}/lib/cmake/sdformat/SDFormatConfig.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\sdformat-6.2\\sdf\\sdf.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\sdformat.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\sdformat.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\sdformat\\SDFormatConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://sdformat.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Simulation Description Format (SDF) parser and description files.

extra:
  recipe-maintainers:
    - seanyen
    - j-rivero
    - conda-forge/ros-core
