{% set repo_name = "sdformat" %}
{% set version = "15.3.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = repo_name  + major_version %}
{% set cxx_name = "lib" + name %}
{% set python_name = name + "-python" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osrf/sdformat/archive/sdformat{{ major_version }}_{{ version }}.tar.gz
    sha256: b187da7a21a6e0f5e2a45f6b4026a1a69fd39e3f50de26f028313595a1c10cfd

build:
  number: 0


outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - ninja                              # [not win]
        - cmake
        - pkg-config
        - python
      host:
        - libgz-cmake4
        - libgz-math8
        - libgz-tools2
        - libgz-utils3
        - urdfdom
        - tinyxml2
        - dlfcn-win32  # [win]
    test:
      commands:
        - test -f ${PREFIX}/include/gz/sdformat{{ version.split('.')[0] }}/sdf/sdf.hh  # [not win]
        - test -f ${PREFIX}/lib/libsdformat{{ version.split('.')[0] }}${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/lib/cmake/sdformat{{ version.split('.')[0] }}/sdformat{{ version.split('.')[0] }}-config.cmake  # [not win]
        - if not exist %LIBRARY_INC%\\gz\\sdformat{{ version.split('.')[0] }}\\sdf\\sdf.hh exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\sdformat{{ version.split('.')[0] }}.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\sdformat{{ version.split('.')[0] }}.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\cmake\\sdformat{{ version.split('.')[0] }}\\sdformat{{ version.split('.')[0] }}-config.cmake exit 1  # [win]

  - name: {{ python_name }}
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - ninja
        - cmake
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - pybind11-abi                           # [build_platform != target_platform]
        - pytest                                 # [build_platform != target_platform]
      host:
        - {{ pin_subpackage(cxx_name, exact=True) }}
        - python
        - pybind11
        - pybind11-abi
        - pytest
        - libgz-math8
        - gz-math8-python
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
        - python
        - gz-math8-python
    test:
      files:
        - sphere.sdf
        - test_sdformat.py
      commands:
        - pip check
        - python test_sdformat.py
      requires:
        - pip
      imports:
        - sdformat15

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
        - {{ pin_subpackage(python_name, max_pin='x.x.x') }}
    test:
      imports:
        - sdformat15


about:
  home: http://sdformat.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Simulation Description Format (SDF) parser and description files.

extra:
  recipe-maintainers:
    - seanyen
    - j-rivero
    - conda-forge/ros-core
    - Tobias-Fischer
    - traversaro
