{% set name = "libsdformat" %}
{% set version = "9.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/osrf/sdformat/get/sdformat{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: fff12c89ba197714cc22eda4933383d21d04f09239b4606703d2256265c83543
    patches:
      - sdformat.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - ninja                              # [not win]
    - ruby                               # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-math6
    - urdfdom
    - boost-cpp
    - tinyxml
    - console_bridge
  run:
    - libignition-math6
    - urdfdom
    - boost-cpp
    - tinyxml
    - console_bridge

test:
  commands:
    - test -f ${PREFIX}/include/sdformat-9.1/sdf/sdf.hh  # [not win]
    - test -f ${PREFIX}/lib/libsdformat9${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/cmake/sdformat9/sdformat9-config.cmake  # [not win]
    - if not exist %LIBRARY_INC%\\sdformat-9.1\\sdf\\sdf.hh exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\sdformat9.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\sdformat9.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\sdformat9\\sdformat9-config.cmake exit 1  # [win]

about:
  home: http://sdformat.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Simulation Description Format (SDF) parser and description files.

extra:
  recipe-maintainers:
    - seanyen
    - j-rivero
    - conda-forge/ros-core
    - Tobias-Fischer
