{% set base_name = "libsdformat" %}
{% set version = "12.4.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osrf/sdformat/archive/sdformat{{ major_version }}_{{ version }}.tar.gz
    sha256: 1feaa2c8867f3dbb3ddc9de34218a27cda0b881432057744b9ef12d4f26604b4
    patches:
      - skipPoseNoValueTest.patch  # [osx]

build:
  number: 0
  skip: false
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja                              # [not win]
    - ruby                               # [not win]
    - ruby 2.7                           # [win]
    - cmake
    - pkg-config
  host:
    - libignition-cmake2
    - libignition-math6
    - libignition-tools1
    - libignition-utils1
    - urdfdom
    - tinyxml2
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/sdformat{{ version.split('.')[0] }}/sdf/sdf.hh  # [not win]
    - test -f ${PREFIX}/lib/libsdformat{{ version.split('.')[0] }}${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/cmake/sdformat{{ version.split('.')[0] }}/sdformat{{ version.split('.')[0] }}-config.cmake  # [not win]
    - if not exist %LIBRARY_INC%\\sdformat-{{ version.split('.')[0] }}.{{ version.split('.')[1] }}\\sdf\\sdf.hh exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\sdformat{{ version.split('.')[0] }}.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\sdformat{{ version.split('.')[0] }}.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\sdformat{{ version.split('.')[0] }}\\sdformat{{ version.split('.')[0] }}-config.cmake exit 1  # [win]

about:
  home: http://sdformat.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Simulation Description Format (SDF) parser and description files.

extra:
  recipe-maintainers:
    - seanyen
    - j-rivero
    - conda-forge/ros-core
    - Tobias-Fischer
    - traversaro
