schema_version: 1

context:
  repo_name: sdformat
  version: 16.0.0
  major_version: "16"
  name: ${{ repo_name }}
  cxx_name: ${{ "lib" + name }}
  python_name: ${{ name + "-python" }}

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/osrf/sdformat/archive/sdformat${{ major_version }}_${{ version }}.tar.gz
    sha256: ff70394ec4ff730aead09b5f7d6529588eadfee2da05a3501d99dcf2e1d0d593

build:
  number: 0

outputs:
  - package:
      name: ${{ cxx_name }}
    build:
      script:
        - if: unix
          then: build_cxx.sh
        - if: win
          then: bld_cxx.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - if: not win
          then:
            - ninja
        - cmake
        - pkg-config
        - python
      host:
        - libgz-cmake
        - libgz-math
        - libgz-tools
        - libgz-utils
        - urdfdom
        - tinyxml2
        - if: win
          then:
            - dlfcn-win32
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    tests:
      - script:
          - if: not win
            then:
              - test -f ${PREFIX}/include/gz/sdformat${{ major_version }}/sdf/sdf.hh
              - test -f ${PREFIX}/lib/cmake/sdformat/sdformat-config.cmake
          - if: unix
            then:
              - test -f ${PREFIX}/lib/libsdformat${SHLIB_EXT}
          - if: win
            then:
              - if not exist %LIBRARY_INC%\\gz\\sdformat${{ major_version }}\\sdf\\sdf.hh exit 1
              - if not exist %LIBRARY_LIB%\\sdformat.lib exit 1
              - if not exist %LIBRARY_BIN%\\sdformat.dll exit 1
              - if not exist %LIBRARY_LIB%\\cmake\\sdformat\\sdformat-config.cmake exit 1
          - cmake-package-check sdformat --targets sdformat::sdformat
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}

  - package:
      name: ${{ python_name }}
    build:
      script:
        - if: unix
          then: build_py.sh
        - if: win
          then: bld_py.bat
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ninja
        - cmake
        - pkg-config
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - pybind11
            - pybind11-abi
            - pytest
      host:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
        - python
        - pybind11
        - pybind11-abi
        - pytest
        - libgz-math
        - gz-math-python 9.*
        # Ensure that gz-math-python and libgz-math have consistency version
        - gz-math 9.*
      run:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
        - python
        - gz-math-python 9.*
        # Ensure that gz-math-python and libgz-math have consistency version
        - gz-math 9.*
    tests:
      - files:
          recipe:
            - sphere.sdf
            - test_sdformat.py
        requirements:
          run:
            - pip
        script:
          - python test_sdformat.py
      - python:
          imports:
            - sdformat

  - package:
      name: ${{ name }}
    requirements:
      run:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
        - ${{ pin_subpackage(python_name, upper_bound='x.x.x') }}
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    tests:
      - python:
          imports:
            - sdformat

about:
  homepage: http://sdformat.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Simulation Description Format (SDF) parser and description files.

extra:
  recipe-maintainers:
    - seanyen
    - j-rivero
    - conda-forge/ros-core
    - Tobias-Fischer
    - traversaro
