bot:
  # See https://github.com/gazebosim/docs/blob/master/tools/versions.md for the up-to-date
  # list of non-EOL distros, please also keep v9 for gazebo-classic even if EOL
  abi_migration_branches:
  - v9
  - v12
  - v14
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
